# -*- coding: utf-8 -*-
"""desafio aula 12

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uDAkXadyShe8nkv_z5gl0ZTWssCPFLqb
"""

def converter_tempo(segundos):
  horas  = segundos // 3600
  minutos = (segundos % 3600) // 60
  segundo = segundos % 60

  return (f'{horas}:{minutos}:{segundo}')

tempo_em_segundos = int(input())

resultado = converter_tempo(tempo_em_segundos)
print(resultado)

x = int(input('Digite a distancia '))

y = float(input('digite o valor de combustivel gasto'))

consumo_medio = x/y

print(f'{consumo_medio: .3f} km/l')

